export default [
  'C:\\DOS\\RUN\\DOS\\RUN',
  'C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC',
  'C:\\Program Files (x86)\\Awkward Family Photos',
  'C:\\Program Files (x86)\\Bad Jokes',
  'C:\\Program Files (x86)\\Common Files\\Adobe',
  'C:\\Program Files (x86)\\Common Files\\Intel\\WirelessCommon',
  'C:\\Program Files (x86)\\Common Files\\Microsoft Shared',
  'C:\\Program Files (x86)\\Common Files\\Oracle\\Java',
  'C:\\Program Files (x86)\\CyberLink',
  'C:\\Program Files (x86)\\Doge Language',
  'C:\\Program Files (x86)\\Dropbox\\Client',
  'C:\\Program Files (x86)\\Futurama Memes',
  'C:\\Program Files (x86)\\Google\\Chrome',
  'C:\\Program Files (x86)\\Google\\Chrome\\Application',
  'C:\\Program Files (x86)\\Java',
  'C:\\Program Files (x86)\\Meme Generator',
  'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16',
  'C:\\Program Files (x86)\\Microsoft SQL Server',
  'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE',
  'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools',
  'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
  'C:\\Program Files (x86)\\Old Internet Explorer',
  'C:\\Program Files (x86)\\Silly Sounds',
  'C:\\Program Files (x86)\\Skype',
  'C:\\Program Files (x86)\\Spongebob Memes',
  'C:\\Program Files (x86)\\Steam',
  'C:\\Program Files',
  'C:\\Program Files\\Adobe\\Adobe Photoshop CC 2021',
  'C:\\Program Files\\Banana Bread Recipes',
  'C:\\Program Files\\Chuck Norris Facts',
  'C:\\Program Files\\Common Files\\Autodesk Shared',
  'C:\\Program Files\\Common Files\\Microsoft Shared',
  'C:\\Program Files\\Common Files\\VMware',
  'C:\\Program Files\\I Can Has Cheezburger',
  'C:\\Program Files\\Kitten Videos',
  'C:\\Program Files\\Microsoft SQL Server',
  'C:\\Program Files\\Mozilla Firefox',
  'C:\\Program Files\\Simpsons Quotes',
  'C:\\Program Files\\Star Wars Quotes',
  'C:\\Program Files\\Windows Defender',
  'C:\\ProgramData\\Microsoft\\Windows Defender\\Platform',
  'C:\\ProgramData\\Microsoft\\Windows\\DeviceMetadataStore',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Dumb Games',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Grumpy Cat Videos',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Nacho Recipes',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Pizza Delivery',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Useless Apps',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Useless Utilities',
  'C:\\ProgramData\\Microsoft\\Windows\\Templates',
  'C:\\ProgramData\\Microsoft\\Windows\\WER',
  'C:\\trash',
  'C:\\Users\\PC',
  'C:\\Users\\Home Computer\\AppData\\Local\\Microsoft\\WindowsApps',
  'C:\\Users\\Home Computer\\AppData\\Local\\Temp',
  'C:\\Users\\Home Computer\\AppData\\Roaming',
  'C:\\Users\\Home Computer\\Desktop',
  'C:\\Users\\Home Computer\\Desktop\\Distracted Boyfriend',
  'C:\\Users\\Home Computer\\Desktop\\Duck Face Selfies',
  'C:\\Users\\Home Computer\\Documents',
  'C:\\Users\\Home Computer\\Documents\\Cat Memes',
  'C:\\Users\\Home Computer\\Documents\\Taco Tuesday',
  'C:\\Users\\Home Computer\\Documents\\Troll Face',
  'C:\\Users\\Home Computer\\Downloads',
  'C:\\Users\\Home Computer\\Downloads',
  'C:\\Users\\Home Computer\\Downloads\\Rick Astley',
  'C:\\Users\\Home Computer\\Downloads\\Shiba Inu',
  'C:\\Users\\Home Computer\\Music',
  'C:\\Users\\Home Computer\\Pictures\\Baby Yoda',
  'C:\\Users\\Home Computer\\Pictures\\Laughing Babies',
  'C:\\Users\\Home Computer\\Pictures\\LOLcats',
  'C:\\Users\\Home Computer\\Videos',
  'C:\\Windows\\Fonts',
  'C:\\Windows\\random\\duckpics',
  'C:\\Windows\\System\\Trojan',
  'C:\\Windows\\system32',
  'C:\\Windows\\System32',
  'C:\\Windows\\System32\\config',
  'C:\\Windows\\System32\\Dad Jokes',
  'C:\\Windows\\System32\\Dramatic Chipmunk',
  'C:\\Windows\\System32\\drivers',
  'C:\\Windows\\System32\\DriverStore\\FileRepository',
  'C:\\Windows\\System32\\GroupPolicy',
  'C:\\Windows\\System32\\LogFiles',
  'C:\\Windows\\System32\\Puns',
  'C:\\Windows\\System32\\Puppy GIFs',
  'C:\\Windows\\System32\\spool\\drivers',
  'C:\\Windows\\System32\\spool\\drivers\\x64',
  'C:\\Windows\\System32\\Tasks',
  'C:\\Windows\\System32\\Tasks',
  'C:\\Windows\\System32\\Tasks\\Lenovo',
  'C:\\Windows\\System32\\Tasks\\Microsoft',
  'C:\\Windows\\System32\\WindowsPowerShell',
  'C:\\Windows\\system420',
  'C:\\Windows\\SysWOW64',
  'C:\\Windows\\SysWOW64\\config\\systemprofile',
  'C:\\Windows\\SysWOW64\\drivers',
  'C:\\Windows\\SysWOW64\\drivers\\etc',
  'C:\\Windows\\SysWOW64\\Macromed',
  'C:\\Windows\\SysWOW64\\Magic 8-Ball',
  'C:\\Windows\\SysWOW64\\Ninja Cat',
  'C:\\Windows\\SysWOW64\\Whoopee Cushion',
  'C:\\Windows\\SysWOW64\\Yodeling Pickle',
  'C:\\Windows\\Temp',
  'C:\\Windows\\Temp\\Hot Potato',
  'C:\\Windows\\Temp\\Hot Sauce',
  'C:\\Windows\\winsxs',
];
