export default [
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\WorldWideWebWide\\',
  'C:\\Program Files\\bonzibuddy\\Updates\\',
  'C:\\Users\\wwwwtsactp\\Documents\\CrowPro\\',
  'C:\\ProgramData\\BestGoats\\Logs\\',
  'C:\\Windows\\System32\\hunter2\\Drivers\\',
  'C:\\Users\\YouMatter\\Desktop\\Take-Chances-And-Get-Messy\\',
  'C:\\Program Files (x86)\\Bluetooth\\Drivers\\',
  'C:\\Users\\Goats\\AppData\\Local\\Beanwork\\',
  'C:\\Windows\\System32\\crowpro\\SysWOW64\\',
  'C:\\ProgramData\\CardRedeemer\\Logs\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\Bluetooth\\',
  'C:\\Program Files\\bonzi\\Updates\\',
  'C:\\Users\\wwwwtsactp\\Documents\\CrowProSurvival\\',
  'C:\\ProgramData\\BestGoats\\Backup\\',
  'C:\\Windows\\System32\\hunter2\\Logs\\',
  'C:\\Users\\YouMatter\\Desktop\\Bean\\',
  'C:\\Program Files (x86)\\Bluetooth\\Settings\\',
  'C:\\Users\\Goats\\AppData\\Local\\Carrot\\',
  'C:\\Windows\\System32\\crowpro\\Samples\\',
  'C:\\ProgramData\\CardRedeemer\\Backup\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\Beanwork\\',
  'C:\\Program Files\\bonzi\\Plugins\\',
  'C:\\Users\\wwwwtsactp\\Documents\\CrowProHunt\\',
  'C:\\ProgramData\\BestGoats\\Temp\\',
  'C:\\Windows\\System32\\hunter2\\Config\\',
  'C:\\Users\\YouMatter\\Desktop\\Bluetooth\\',
  'C:\\Program Files (x86)\\GoatsVsZombies\\',
  'C:\\Users\\Goats\\AppData\\Local\\CrowProEncounter\\',
  'C:\\Windows\\System32\\crowpro\\Config\\',
  'C:\\ProgramData\\CardRedeemer\\Temp\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\BluetoothHeadset\\',
  'C:\\Program Files\\bonzi\\Backup\\',
  'C:\\Users\\wwwwtsactp\\Documents\\CrowProWarrior\\',
  'C:\\ProgramData\\BestGoats\\Downloads\\',
  'C:\\Windows\\System32\\hunter2\\Settings\\',
  'C:\\Users\\YouMatter\\Desktop\\CardRedemption\\',
  'C:\\Program Files (x86)\\BluetoothMouse\\',
  'C:\\Users\\Goats\\AppData\\Local\\CrowProQuest\\',
  'C:\\Windows\\System32\\crowpro\\Updates\\',
  'C:\\ProgramData\\CardRedeemer\\Downloads\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\BluetoothKeyboard\\',
  'C:\\Program Files\\bonzi\\Downloads\\',
  'C:\\Users\\wwwwtsactp\\Documents\\CrowProDefender\\',
  'C:\\ProgramData\\BestGoats\\Settings\\',
  'C:\\Windows\\System32\\hunter2\\Plugins\\',
  'C:\\Users\\YouMatter\\Desktop\\CrowPro\\',
  'C:\\Program Files (x86)\\BluetoothAdapter\\',
  'C:\\Users\\Goats\\AppData\\Local\\CrowProInvasion\\',
  'C:\\Windows\\System32\\crowpro\\Backup\\',
  'C:\\ProgramData\\CardRedeemer\\Settings\\',
  'C:\\Users\\EachAndEvery\\AppData\\Ro',
  'C:\\Windows\\System32\\UpdogHunter2Silly\\',
  'C:\\Windows\\System32\\UpdogBluetoothSilly\\',
  'C:\\Windows\\System32\\TropicalThunderstorms\\StormySeas\\',
  'C:\\Windows\\System32\\SunsetSerenade\\OceanicTides\\',
  'C:\\Windows\\System32\\RapGodHunter2Bonkers\\',
  'C:\\Windows\\System32\\RapGodHunter2Absurd\\',
  'C:\\Windows\\System32\\RapGodBluetoothTaco\\',
  'C:\\Windows\\System32\\PecanHunter2Ludicrous\\',
  'C:\\Windows\\System32\\PecanBluetoothGiggles\\',
  'C:\\Windows\\System32\\MountainHigh\\WinterWonderland\\',
  'C:\\Windows\\System32\\MayonnaiseBluetoothGlee\\',
  'C:\\Windows\\System32\\GraffitiArt\\UrbanCulture\\',
  'C:\\Windows\\System32\\DeepSeaDiving\\UnderwaterAdventures\\',
  'C:\\Windows\\System32\\AuroraBorealis\\NorthernLights\\',
  'C:\\Users\\YouMatter\\Desktop\\RapGodHuntWild\\',
  'C:\\Users\\YouMatter\\Desktop\\RapGodEverydayPineapple\\',
  'C:\\Users\\YouMatter\\Desktop\\RapGodEverydayKooky\\',
  'C:\\Users\\YouMatter\\Desktop\\PecanBeanHilarious\\',
  'C:\\Users\\wwwwtsactp\\Documents\\UpdogGoatsNonsense\\',
  'C:\\Users\\wwwwtsactp\\Documents\\RapGodGoatsKooky\\',
  'C:\\Users\\wwwwtsactp\\Documents\\PecanGoatsLoony\\',
  'C:\\Users\\wwwwtsactp\\Documents\\MayonnaiseBeanCrazy\\',
  'C:\\Users\\WildWestCowboy\\WesternAdventures\\CowboyFiles\\',
  'C:\\Users\\TropicalParadise\\CoconutIsland\\SandyBeaches\\',
  'C:\\Users\\SurfingSunsets\\BeachBumming\\TropicalFiles\\',
  'C:\\Users\\SpiritualSeeker\\ZenMeditation\\Mindfulness\\',
  'C:\\Users\\RobotRanch\\TechWorld\\InnovativeIdeas\\',
  'C:\\Users\\MusicMuse\\MelodicMasterpieces\\MusicDocs\\',
  'C:\\Users\\MountainHiker\\HikingAdventures\\NaturePhotos\\',
  'C:\\Users\\MoonlitNight\\StarrySkies\\MysteriousFiles\\',
  'C:\\Users\\MidnightRider\\PsychedelicSunrise\\RockyRoads\\',
  'C:\\Users\\MagicalUnicorn\\RainbowFields\\MagicalFiles\\',
  'C:\\Users\\HippieJazz\\SweaterWeather\\SmokeyMountain\\Files\\',
  'C:\\Users\\Goats\\AppData\\Local\\UpdogCrowProCrazy\\',
  'C:\\Users\\Goats\\AppData\\Local\\RapGodMayonnaiseBloop\\',
  'C:\\Users\\Goats\\AppData\\Local\\PecanCrowProHilarity\\',
  'C:\\Users\\Goats\\AppData\\Local\\PecanCrowProHilarious\\',
  'C:\\Users\\Goats\\AppData\\Local\\MayonnaiseCrowProBizarre\\',
  'C:\\Users\\FunkyMonkey\\JungleJams\\WildFiles\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\UpdogBluetoothBoop\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\RapGodUpdogSilly\\',
  'C:\\Users\\EachAndEvery\\AppData\\Roaming\\MayonnaiseBluetoothJazzy\\',
  'C:\\Program Files (x86)\\UpdogBluetoothFunky\\',
  'C:\\Program Files (x86)\\RapGodCardRedeemerHoopla\\',
  'C:\\Program Files (x86)\\OceanicWondersCorp\\SeasideSplendor\\SeaFiles\\',
  'C:\\Program Files (x86)\\NeonRainbowCorp\\GlitterGalore\\Sparkles\\',
  'C:\\Program Files (x86)\\MayonnaiseCardRedeemerWhimsy\\',
  'C:\\Program Files (x86)\\MayonnaiseCardRedeemerMystery\\',
  'C:\\Program Files (x86)\\LoudFrogLLC\\CherryBlossom\\CoolStuff\\',
  'C:\\Program Files\\WanderingNomadCorp\\DesertExplorer\\Adventures\\',
  'C:\\Program Files\\UpdogPecanJammin\\',
  'C:\\Program Files\\RapGodPecanBanana\\',
  'C:\\Program Files\\NinjaWarriorCorp\\StealthMissions\\NinjaFiles\\',
  'C:\\Program Files\\MayonnaisePecanHysterical\\',
  'C:\\Program Files\\MayonnaiseBluetoothSilly\\',
  'C:\\Program Files\\GoldenRetrieverCorp\\StarryNights\\DoggyFiles\\',
  'C:\\ProgramData\\ZenGardenInc\\BuddhaWisdom\\Enlightenment\\',
  'C:\\ProgramData\\UpdogHunter2Whimsical\\',
  'C:\\ProgramData\\UpdogHunter2Wacky\\',
  'C:\\ProgramData\\UpdogCardRedeemerWacky\\',
  'C:\\ProgramData\\SapphireSkyLLC\\SkyHigh\\CloudFiles\\',
  'C:\\ProgramData\\RapGodCardRedeemerWild\\',
  'C:\\ProgramData\\RapGodBluetoothHilarious\\',
  'C:\\ProgramData\\PecanCardRedeemerSilly\\',
  'C:\\ProgramData\\NeonNightsLLC\\GlowInTheDark\\Lightning\\',
  'C:\\ProgramData\\MayonnaiseCardRedeemerZany\\',
  'C:\\ProgramData\\MayonnaiseBluetoothJester\\',
  'C:\\ProgramData\\MagicalMysteryLLC\\EnchantedForest\\Fairytales\\',
  'C:\\ProgramData\\DragonFireCorp\\AncientArtifacts\\SecretDocs\\',
  'C:\\ProgramData\\ChirpingFlamingoLabs\\FloweryPiano\\Docs\\',
  'C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC',
  'C:\\Program Files (x86)\\Awkward Family Photos',
  'C:\\Program Files (x86)\\Bad Jokes',
  'C:\\Program Files (x86)\\Common Files\\Adobe',
  'C:\\Program Files (x86)\\Common Files\\Intel\\WirelessCommon',
  'C:\\Program Files (x86)\\Common Files\\Microsoft Shared',
  'C:\\Program Files (x86)\\Common Files\\Oracle\\Java',
  'C:\\Program Files (x86)\\CyberLink',
  'C:\\Program Files (x86)\\Doge Language',
  'C:\\Program Files (x86)\\Dropbox\\Client',
  'C:\\Program Files (x86)\\Futurama Memes',
  'C:\\Program Files (x86)\\Google\\Chrome',
  'C:\\Program Files (x86)\\Google\\Chrome\\Application',
  'C:\\Program Files (x86)\\Java',
  'C:\\Program Files (x86)\\Meme Generator',
  'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16',
  'C:\\Program Files (x86)\\Microsoft SQL Server',
  'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE',
  'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools',
  'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
  'C:\\Program Files (x86)\\Old Internet Explorer',
  'C:\\Program Files (x86)\\Silly Sounds',
  'C:\\Program Files (x86)\\Skype',
  'C:\\Program Files (x86)\\Spongebob Memes',
  'C:\\Program Files (x86)\\Steam',
  'C:\\Program Files',
  'C:\\Program Files\\Adobe\\Adobe Photoshop CC 2021',
  'C:\\Program Files\\Banana Bread Recipes',
  'C:\\Program Files\\Chuck Norris Facts',
  'C:\\Program Files\\Common Files\\Autodesk Shared',
  'C:\\Program Files\\Common Files\\Microsoft Shared',
  'C:\\Program Files\\Common Files\\VMware',
  'C:\\Program Files\\I Can Has Cheezburger',
  'C:\\Program Files\\Kitten Videos',
  'C:\\Program Files\\Microsoft SQL Server',
  'C:\\Program Files\\Mozilla Firefox',
  'C:\\Program Files\\Simpsons Quotes',
  'C:\\Program Files\\Star Wars Quotes',
  'C:\\Program Files\\Windows Defender',
  'C:\\ProgramData\\Microsoft\\Windows Defender\\Platform',
  'C:\\ProgramData\\Microsoft\\Windows\\DeviceMetadataStore',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Dumb Games',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Grumpy Cat Videos',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Nacho Recipes',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Pizza Delivery',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Useless Apps',
  'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Useless Utilities',
  'C:\\ProgramData\\Microsoft\\Windows\\Templates',
  'C:\\ProgramData\\Microsoft\\Windows\\WER',
  'C:\\trash',
  'C:\\Users\\PC',
  'C:\\Users\\Home Computer\\AppData\\Local\\Microsoft\\WindowsApps',
  'C:\\Users\\Home Computer\\AppData\\Local\\Temp',
  'C:\\Users\\Home Computer\\AppData\\Roaming',
  'C:\\Users\\Home Computer\\Desktop',
  'C:\\Users\\Home Computer\\Desktop\\Distracted Boyfriend',
  'C:\\Users\\Home Computer\\Desktop\\Duck Face Selfies',
  'C:\\Users\\Home Computer\\Documents',
  'C:\\Users\\Home Computer\\Documents\\Cat Memes',
  'C:\\Users\\Home Computer\\Documents\\Taco Tuesday',
  'C:\\Users\\Home Computer\\Documents\\Troll Face',
  'C:\\Users\\Home Computer\\Downloads',
  'C:\\Users\\Home Computer\\Downloads',
  'C:\\Users\\Home Computer\\Downloads\\Rick Astley',
  'C:\\Users\\Home Computer\\Downloads\\Shiba Inu',
  'C:\\Users\\Home Computer\\Music',
  'C:\\Users\\Home Computer\\Pictures\\Baby Yoda',
  'C:\\Users\\Home Computer\\Pictures\\Laughing Babies',
  'C:\\Users\\Home Computer\\Pictures\\LOLcats',
  'C:\\Users\\Home Computer\\Videos',
  'C:\\Windows\\Fonts',
  'C:\\Windows\\random\\duckpics',
  'C:\\Windows\\System\\Trojan',
  'C:\\Windows\\system32',
  'C:\\Windows\\System32',
  'C:\\Windows\\System32\\config',
  'C:\\Windows\\System32\\Dad Jokes',
  'C:\\Windows\\System32\\Dramatic Chipmunk',
  'C:\\Windows\\System32\\drivers',
  'C:\\Windows\\System32\\DriverStore\\FileRepository',
  'C:\\Windows\\System32\\GroupPolicy',
  'C:\\Windows\\System32\\LogFiles',
  'C:\\Windows\\System32\\Puns',
  'C:\\Windows\\System32\\Puppy GIFs',
  'C:\\Windows\\System32\\spool\\drivers',
  'C:\\Windows\\System32\\spool\\drivers\\x64',
  'C:\\Windows\\System32\\Tasks',
  'C:\\Windows\\System32\\Tasks',
  'C:\\Windows\\System32\\Tasks\\Lenovo',
  'C:\\Windows\\System32\\Tasks\\Microsoft',
  'C:\\Windows\\System32\\WindowsPowerShell',
  'C:\\Windows\\system420',
  'C:\\Windows\\SysWOW64',
  'C:\\Windows\\SysWOW64\\config\\systemprofile',
  'C:\\Windows\\SysWOW64\\drivers',
  'C:\\Windows\\SysWOW64\\drivers\\etc',
  'C:\\Windows\\SysWOW64\\Macromed',
  'C:\\Windows\\SysWOW64\\Magic 8-Ball',
  'C:\\Windows\\SysWOW64\\Ninja Cat',
  'C:\\Windows\\SysWOW64\\Whoopee Cushion',
  'C:\\Windows\\SysWOW64\\Yodeling Pickle',
  'C:\\Windows\\Temp',
  'C:\\Windows\\Temp\\Hot Potato',
  'C:\\Windows\\Temp\\Hot Sauce',
  'C:\\Windows\\winsxs',
];
